-- SENTENCIAS DDL
-- CREATE TABLE

CREATE TABLE alumno (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nro_documento VARCHAR(20) NOT NULL,
    Nombre VARCHAR(255) NOT NULL,
    Email VARCHAR(100)
);

-- ALTERAR UN TABLA
ALTER TABLE alumno ADD COLUMN Nota INT DEFAULT 0;

-- ELIMINAR UNA TABLA
DROP TABLE alumno;