-- SENTENCIAS DDL
-- CREATE TABLE
USE db_g6;

CREATE TABLE alumno (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nro_documento VARCHAR(20) NOT NULL,
    Nombre VARCHAR(255) NOT NULL,
    Email VARCHAR(100)
);

-- ALTERAR UN TABLA
ALTER TABLE alumno ADD COLUMN Nota INT DEFAULT 0;

-- ELIMINAR UNA TABLA
DROP TABLE alumno;

CREATE TABLE empresa (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    Ruc VARCHAR(12) NOT NULL UNIQUE,
    Razon_Social VARCHAR(125) NOT NULL,
    Direccion TEXT
);